c_compiler_version:     # [osx]
  - 19                  # [osx]
cxx_compiler_version:   # [osx]
  - 19                  # [osx]

channel_sources:                            # [osx]
  - conda-forge/label/llvm_rc,conda-forge   # [osx]
