{% set version = "2.0.12" %}

package:
  name: sdl2
  version: {{ version }}

source:
  url:  https://www.libsdl.org/release/SDL2-{{ version }}.tar.gz
  sha256: 349268f695c02efbc9b9148a70b85e58cefbbf704abd3e91be654db7f1e2c863
  patches:
    - msvc2015.patch  # [win]
    - msvc9_empty_array.patch  # [win and c_compiler == 'vs2008']
    - isOperatingSystemAtLeastVersion-not-found.patch
    - fixLibSuffixOSX.patch

build:
  number: 1

requirements:
  build:
    - cmake  # [win]
    - make  # [unix]
    - autoconf  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - xorg-libx11  # [linux]
    - xorg-libxext  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
  host:
    - xorg-libx11  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libxfixes  # [linux]
  run:
    - xorg-libx11  # [linux]
    - xorg-libxext  # [linux]

test:
  commands:
    - sdl2-config --version  # [not win]

about:
  home: https://www.libsdl.org/index.php
  license: Zlib
  license_file: COPYING.txt
  summary: "Low-level access to audio, keyboard, mouse, joystick, and graphics"
  description: |
    Simple DirectMedia Layer is a cross-platform development library designed to
    provide low level access to audio, keyboard, mouse, joystick, and graphics
    hardware via OpenGL and Direct3D.
  doc_url: https://wiki.libsdl.org/FrontPage
  dev_url: http://hg.libsdl.org/SDL

extra:
  recipe-maintainers:
    - dschreij
    - matham
