{% set name = "sdl2" %}
{% set version = "2.0.22" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://www.libsdl.org/release/SDL2-{{ version }}.tar.gz
  sha256: fe7cbf3127882e3fc7259a75a0cb585620272c51745d3852ab9dd87960697f2e
  patches:
    - msvc2015.patch  # [win]
    - msvc9_empty_array.patch  # [win and c_compiler == 'vs2008']

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - cmake  # [win]
    - make  # [unix]
    - autoconf  # [not win]
    - gnuconfig   # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - xorg-libx11  # [linux]
    - xorg-libxext  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
  host:
    - xorg-libx11  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libxfixes  # [linux]
  run:
    - xorg-libx11  # [linux]
    - xorg-libxext  # [linux]

test:
  commands:
    - sdl2-config --version  # [not win]

about:
  home: https://www.libsdl.org/index.php
  license: Zlib
  license_file: LICENSE.txt
  summary: Low-level access to audio, keyboard, mouse, joystick, and graphics
  description: |
    Simple DirectMedia Layer is a cross-platform development library designed to
    provide low level access to audio, keyboard, mouse, joystick, and graphics
    hardware via OpenGL and Direct3D.
  doc_url: https://wiki.libsdl.org/FrontPage
  dev_url: http://hg.libsdl.org/SDL

extra:
  recipe-maintainers:
    - dschreij
    - matham
