{% set version = "2.0.8" %}

package:
  name: sdl2
  version: {{ version }}

source:
  url:  https://www.libsdl.org/release/SDL2-{{ version }}.tar.gz
  sha256: edc77c57308661d576e843344d8638e025a7818bff73f8fbfab09c3c5fd092ec

build:
  number: 1001

requirements:
  build:
    - cmake  # [win]
    - autoconf  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - xorg-libx11  # [linux]
    - xorg-libxext  # [linux]
  run:
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
    - xorg-libxext  # [linux]

test:
  commands:
    - sdl2-config --version  # [not win]

about:
  home: https://www.libsdl.org/index.php
  license: Public Domain/ZLIB
  license_file: COPYING.txt
  summary: "Low-level access to audio, keyboard, mouse, joystick, and graphics"
  description: |
    Simple DirectMedia Layer is a cross-platform development library designed to
    provide low level access to audio, keyboard, mouse, joystick, and graphics
    hardware via OpenGL and Direct3D.
  doc_url: https://wiki.libsdl.org/FrontPage
  dev_url: http://hg.libsdl.org/SDL

extra:
  recipe-maintainers:
    - dschreij
