{% set name = "SDL2" %}
{% set version = "2.0.4" %}
{% set sha256 = "da55e540bf6331824153805d58b590a29c39d2d506c6d02fa409aedeab21174b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn:  {{ name }}-{{ version }}.tar.gz
  url:  https://www.libsdl.org/release/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]

requirements:
  build:
    # Add python for feature activation
    - python  # [win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
    - cmake  # [win]
    - autoconf  # [unix]
  run:
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]

test:
  requires:
    - python {{ environ['PY_VER'] + '*' }}  # [win]
  commands:
    - sdl2-config --version  # [unix]

about:
  home: https://www.libsdl.org/index.php
  license: Public Domain/ZLIB
  license_file: COPYING.txt
  summary: "Low-level access to audio, keyboard, mouse, joystick, and graphics"
  description: |
    Simple DirectMedia Layer is a cross-platform development library designed to 
    provide low level access to audio, keyboard, mouse, joystick, and graphics 
    hardware via OpenGL and Direct3D.
  doc_url: https://wiki.libsdl.org/FrontPage
  dev_url: http://hg.libsdl.org/SDL

extra:
  recipe-maintainers:
    - dschreij
