{% set version = "2.28.3" %}

package:
  name: sdl2
  version: {{ version }}

source:
  url: https://github.com/libsdl-org/SDL/releases/download/release-{{ version }}/SDL2-{{ version }}.tar.gz
  sha256: 7acb8679652701a2504d734e2ba7543ec1a83e310498ddd22fd44bf965eb5518

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("sdl2", max_pin='x') }}

requirements:
  build:
    - cmake  # [win]
    - make  # [unix]
    - autoconf  # [not win]
    - gnuconfig   # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - xorg-libx11  # [linux]
    - xorg-libxext  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - pulseaudio  # [linux]
  host:
    - xorg-libx11  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libxfixes  # [linux]
    - pulseaudio  # [linux]
  run:
    - xorg-libx11  # [linux]
    - xorg-libxext  # [linux]

test:
  commands:
    - sdl2-config --version  # [not win]

about:
  home: https://www.libsdl.org/index.php
  license: Zlib
  license_file: LICENSE.txt
  summary: Low-level access to audio, keyboard, mouse, joystick, and graphics
  description: |
    Simple DirectMedia Layer is a cross-platform development library designed to
    provide low level access to audio, keyboard, mouse, joystick, and graphics
    hardware via OpenGL and Direct3D.
  doc_url: https://wiki.libsdl.org/FrontPage
  dev_url: http://hg.libsdl.org/SDL

extra:
  recipe-maintainers:
    - dschreij
    - matham
