appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: TCREWpVL2g4GYmMxo8j7PB0o+J5Xnnq35mWsCGHXywuNNmhn7Z8TNTRKvGGm+Tuoi23/Yi4As+pnjHDNWXyFTy7SQrJ0oeVRMCzd1bKff47sZZ6pj6yBw/Y/VRBEIjys1SbkZWk63Vjd6XByQNGAfKuIc8Ak4gHls8npKG1AutFwQRE64tlHTQgQo5QKwinjmMgia/8acsAK1momCNP8o1jnTejUI4hu8F3/QsUgZx/zKswXz3n/6+Y1p6MgsQw1TSdODlbjeWwnYAiqfoGDI3q2ZvkBynarW7VauWTbOYdy9DgTH5R2+f35MOdPJmjMqsgULUJJCJX/lpLJSoWMx2zP3kyJ45Vse694j/AYZZFWcQsizOkva1iIWRBMllLG0bEQoUtHNlBooQG1hzBxyyyr80PHggrd/fYeHxrJAZmJLlPiIWD6qhgiHwP0oCh2STtVCg68GiEpYdHoHyOym+Zw6BauAspmbA1bf7LxP5X38+zyfhUkWH+9jvfcVW6Ctk3BRw7NGadEeofMD45UT//a7I++i5pZpMfd7MNB3Kj3+qnFzBpRVjLyW1gPWsvOtl7TZ6CzyvyZmGJhxOd5FIGK/c7YJee+VxD0r6OmL4Z3LIl1gtmfxRlsnhtj+D5wrYsi6Qd9GUN1oVs9sqlnM9smY2KCmvQOmBqfQYUKIjw=}
provider:
  win: azure
